services:
  app:
    build: .
    ports:
      - '8080:8080'
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: 'true'
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    stdin_open: true
    tty: true
volumes:
  node_modules:
